version: 1.0.{build}
branches:
  only:
  - main
  - develop
image: Ubuntu2004
init:
# C++ compiler:           clang g++ make
# juce_core:              libcurl4-openssl-dev
# juce_graphics:          libfreetype6-dev
# juce_audio_devices:     libasound2-dev libjack-jackd2-dev
# juce_audio_processors:  ladspa-sdk
# juce_gui_basics:        libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev
# juce_opengl:            libglu1-mesa-dev mesa-common-dev
- sh: >-
    yes |Â sudo apt-get update
    
    yes | sudo apt install clang g++ make

    yes | sudo apt install libcurl4-openssl-dev

    yes | sudo apt install libfreetype6-dev

    yes | sudo apt install libasound2-dev libjack-jackd2-dev

    yes | sudo apt install ladspa-sdk

    yes | sudo apt install libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev

    yes | sudo apt install libglu1-mesa-dev mesa-common-dev
install:
- sh: >-
    cd "$APPVEYOR_BUILD_FOLDER"

    git submodule update --init --recursive
build_script:
- sh: >-
    cd Resources/Deployment/Linux

    sudo chmod +x build_Mema.sh

    ./build_Mema.sh
notifications:
- provider: Email
  to:
  - christianahrens@me.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false